'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Agencias
    Public Property id_agencia As Integer
    Public Property id_corporativo As Integer
    Public Property id_pais As Integer
    Public Property nombre As String
    Public Property direccion As String
    Public Property estado_provincia As String
    Public Property ciudad As String
    Public Property telefono As String
    Public Property fecha_alta As Nullable(Of Date)
    Public Property fecha_termino As Nullable(Of Date)
    Public Property id_moneda As Integer
    Public Property limite_credito As Nullable(Of Decimal)
    Public Property NIT As String
    Public Property requiere_asignacion As Boolean
    Public Property id_recibo As Integer
    Public Property factor As Decimal
    Public Property esquema_por_factor As Boolean
    Public Property costo_adicional As Decimal
    Public Property guia_estafeta As Boolean
    Public Property noexterior As String
    Public Property colonia As String
    Public Property municipio As String
    Public Property codigo_postal As String
    Public Property email As String
    Public Property RFC As String

    Public Overridable Property D_TARIFAS_AGENCIA As ICollection(Of TarifaAgencia) = New HashSet(Of TarifaAgencia)
    Public Overridable Property D_ENVIOS_PREASIGNADOS As ICollection(Of EnviosPreAsignados) = New HashSet(Of EnviosPreAsignados)

End Class
