'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditLog
    Public Property AuditLogId As Integer
    Public Property Tabla As String
    Public Property Columna As String
    Public Property ValorAnterior As String
    Public Property ValorActual As String
    Public Property Fecha As Nullable(Of Date)
    Public Property Usuario As Nullable(Of Integer)
    Public Property IdEnvio As Nullable(Of Integer)

End Class
