'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CiudadesRutas
    Public Property id_ciudad_ruta As Integer
    Public Property id_ciudad As Integer
    Public Property id_ruta As Integer

End Class
