'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property id_cliente As Integer
    Public Property id_pais As Integer
    Public Property nombre As String
    Public Property empresa As String
    Public Property apellidos As String
    Public Property calle As String
    Public Property noexterior As Nullable(Of Integer)
    Public Property nointerior As String
    Public Property direccion2 As String
    Public Property colonia As String
    Public Property ciudad As String
    Public Property municipio As String
    Public Property estadoprovincia As String
    Public Property telefono As String
    Public Property codigo_postal As String
    Public Property email As String
    Public Property NIT As String

    Public Overridable Property D_ENVIOS_DATOS As ICollection(Of EnvioDatos) = New HashSet(Of EnvioDatos)

End Class
