'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cobertura
    Public Property id As Integer
    Public Property codigo_postal As String
    Public Property municipio As String
    Public Property estado As String
    Public Property siglas_plaza As String
    Public Property lunes As Boolean
    Public Property martes As Boolean
    Public Property miercoles As Boolean
    Public Property jueves As Boolean
    Public Property viernes As Boolean
    Public Property sabado As Boolean
    Public Property domingo As Boolean
    Public Property periodicidad As String
    Public Property ocurre As Boolean
    Public Property reexpedicion As Boolean
    Public Property garantia_maxima As String
    Public Property ciudad As String
    Public Property siglas_plaza_tarimas As String
    Public Property area_extendida As Nullable(Of Integer)
    Public Property DL_Paqueteria As Nullable(Of Integer)
    Public Property DL_Express As Nullable(Of Integer)
    Public Property DL_Tarimas As Nullable(Of Integer)

End Class
