'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeliveryConfirmation
    Public Property DeliveryConfirmationId As Integer
    Public Property UserId As Integer
    Public Property ShipmentId As Integer
    Public Property TrackId As String
    Public Property SignImage As Byte()
    Public Property SignName As String
    Public Property Comments As String
    Public Property DeliveryDate As Date
    Public Property CreatedOn As Date
    Public Property DeliveryImage As Byte()

End Class
