'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Envio
    Public Property id_envio As Integer
    Public Property precio As Decimal
    Public Property valor_seguro As Decimal
    Public Property id_tarifa_agencia As Integer
    Public Property id_codigo_promocion As Nullable(Of Integer)
    Public Property total_envio As Decimal
    Public Property fecha As Date
    Public Property fecha_corte As Nullable(Of Date)
    Public Property instrucciones_entrega As String
    Public Property id_usuario As Integer
    Public Property id_ruta As Nullable(Of Integer)
    Public Property largo As Nullable(Of Decimal)
    Public Property ancho As Nullable(Of Decimal)
    Public Property alto As Nullable(Of Decimal)
    Public Property peso As Nullable(Of Decimal)
    Public Property Referencia1 As String
    Public Property id_contenido As Nullable(Of Integer)
    Public Property id_status As Integer
    Public Property valor_aduana As Nullable(Of Decimal)
    Public Property Referencia_FedEx As String
    Public Property Referencia_USPS As String
    Public Property id_subproducto As Nullable(Of Integer)
    Public Property contenedores As String
    Public Property observaciones As String

    Public Overridable Property D_TARIFAS_AGENCIA As TarifaAgencia
    Public Overridable Property D_ENVIOS_PREASIGNADOS As EnviosPreAsignados

End Class
