'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EnvioComentario
    Public Property id_comentario As Integer
    Public Property id_agente As Integer
    Public Property id_usuario As Integer
    Public Property fecha As Nullable(Of Date)
    Public Property comentario As String
    Public Property tipo_comentario As Byte
    Public Property id_envio As Nullable(Of Integer)

End Class
