'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EnviosPreAsignados
    Public Property id_envio As Integer
    Public Property id_agencia As Integer
    Public Property fecha As Nullable(Of Date)
    Public Property id_tarifa_tipo As Nullable(Of Integer)
    Public Property tarifa As Nullable(Of Decimal)
    Public Property id_moneda As Nullable(Of Integer)

    Public Overridable Property C_AGENCIAS As Agencias
    Public Overridable Property D_ENVIOS As Envio
    Public Overridable Property D_ENVIOS_DATOS As EnvioDatos

End Class
