'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstafetaFrecuenciaCotizador
    Public Property id As Integer
    Public Property EsPaquete As Nullable(Of Boolean)
    Public Property Largo As Nullable(Of Double)
    Public Property Peso As Nullable(Of Double)
    Public Property Alto As Nullable(Of Double)
    Public Property Ancho As Nullable(Of Double)
    Public Property OcurreForzoso As String
    Public Property Frecuencia As String
    Public Property CostoReexpedicion As String
    Public Property ExistenteSiglaOri As String
    Public Property ExistenteSiglaDes As String
    Public Property Lunes As String
    Public Property Martes As String
    Public Property Miercoles As String
    Public Property Jueves As String
    Public Property Viernes As String
    Public Property Sabado As String
    Public Property Domingo As String
    Public Property id_envio As Integer
    Public Property FechaCotizacion As Nullable(Of Date)
    Public Property identificador As Nullable(Of System.Guid)

End Class
