'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstafetaRequestResponse
    Public Property id As Integer
    Public Property metodo As String
    Public Property request As String
    Public Property response As String
    Public Property fecha As Nullable(Of Date)
    Public Property cuenta As Nullable(Of Integer)
    Public Property imagenBase64 As String

End Class
