'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstafetaTipoServicio
    Public Property id As Integer
    Public Property id_envio As Integer
    Public Property DescripcionServicio As String
    Public Property TipoEnvioRes As Nullable(Of Decimal)
    Public Property AplicaCotizacion As String
    Public Property TarifaBase As Nullable(Of Decimal)
    Public Property CCTarifaBase As Nullable(Of Decimal)
    Public Property CargosExtra As Nullable(Of Decimal)
    Public Property SobrePeso As Nullable(Of Decimal)
    Public Property CCSobrePeso As Nullable(Of Decimal)
    Public Property CostoTotal As Nullable(Of Decimal)
    Public Property Peso As Nullable(Of Decimal)
    Public Property AplicaServicio As String
    Public Property FechaCotizacion As Nullable(Of Date)
    Public Property Selecccionado As Nullable(Of Boolean)

End Class
