'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstafetaLabel
    Public Property id As Integer
    Public Property id_envio As Nullable(Of Integer)
    Public Property labelPDF As Byte()
    Public Property trackId As String
    Public Property fecha As Nullable(Of Date)

End Class
