'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaqueteExpressTipoPaquete
    Public Property id As Integer
    Public Property id_envio As Integer
    Public Property cantidad As Integer
    Public Property contenido As String
    Public Property tipoId As Integer
    Public Property tipo As String
    Public Property alto As Decimal
    Public Property largo As Decimal
    Public Property ancho As Decimal
    Public Property peso As Decimal
    Public Property fecha As Date
    Public Property seguro As Decimal
    Public Property servicioSat As Integer

End Class
