'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sepomex
    Public Property d_codigo As String
    Public Property d_asenta As String
    Public Property d_tipo_asenta As String
    Public Property D_mnpio As String
    Public Property d_estado As String
    Public Property d_ciudad As String
    Public Property d_CP As String
    Public Property c_estado As String
    Public Property c_oficina As String
    Public Property c_CP As String
    Public Property c_tipo_asenta As String
    Public Property c_mnpio As String
    Public Property id_asenta_cpcons As String
    Public Property d_zona As String
    Public Property c_cve_ciudad As String
    Public Property id_estado As Integer
    Public Property estado_codigo As String

End Class
