'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class SiExProEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SiExProEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property C_AGENCIAS() As DbSet(Of Agencias)
    Public Overridable Property C_CLIENTES() As DbSet(Of Cliente)
    Public Overridable Property C_DESTINATARIOS() As DbSet(Of Destinatario)
    Public Overridable Property D_ENVIOS() As DbSet(Of Envio)
    Public Overridable Property D_ENVIOS_DATOS() As DbSet(Of EnvioDatos)
    Public Overridable Property D_TARIFAS_AGENCIA() As DbSet(Of TarifaAgencia)
    Public Overridable Property D_ENVIO_COMENTARIOS() As DbSet(Of EnvioComentario)
    Public Overridable Property D_CIUDADES_RUTAS() As DbSet(Of CiudadesRutas)
    Public Overridable Property D_ESTAFETA_FRECUENCIA_COTIZADOR() As DbSet(Of EstafetaFrecuenciaCotizador)
    Public Overridable Property D_ESTAFETA_TIPO_SERVICIO() As DbSet(Of EstafetaTipoServicio)
    Public Overridable Property D_ESTAFETA_LABEL() As DbSet(Of EstafetaLabel)
    Public Overridable Property C_ESTADOS_GOMBAR() As DbSet(Of EstadosGombar)
    Public Overridable Property C_ZONAS() As DbSet(Of Zonas)
    Public Overridable Property D_COBERTURAS() As DbSet(Of Cobertura)

    Public Overridable Function sp_Select_envios_comentarios_pendientes(id_oficina As Nullable(Of Integer)) As ObjectResult(Of SelectEnviosComentariosPendientesResult)
        Dim id_oficinaParameter As ObjectParameter = If(id_oficina.HasValue, New ObjectParameter("id_oficina", id_oficina), New ObjectParameter("id_oficina", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectEnviosComentariosPendientesResult)("sp_Select_envios_comentarios_pendientes", id_oficinaParameter)
    End Function

End Class
