'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TarifaAgenciaDliverExpress
    Public Property ID As Integer
    Public Property ID_AGENCIA As Nullable(Of Integer)
    Public Property ID_ZONA As Nullable(Of Integer)
    Public Property ID_CUENTA As Nullable(Of Integer)
    Public Property SERVICE_ID As Nullable(Of Integer)
    Public Property PESO_LIMITE_INFERIOR As Nullable(Of Double)
    Public Property PESO_LIMITE_SUPERIOR As Nullable(Of Double)
    Public Property PRECIO As Nullable(Of Decimal)
    Public Property PRECIO_KILO As Nullable(Of Decimal)
    Public Property PRECIO_KILO_ADICIONAL As Nullable(Of Decimal)
    Public Property PRECIO_AREA_EXTENDIDA As Nullable(Of Decimal)
    Public Property PRECIO_EXCESO_DIMENSIONES As Nullable(Of Decimal)
    Public Property IsDeleted As Nullable(Of Integer)

End Class
