'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TarifaAgenciaPaqueteExpress
    Public Property ID_TARIFAS_AGENCIA_PAQUETE_EXPRESS As Integer
    Public Property ID_AGENCIA As Nullable(Of Integer)
    Public Property Tarifa As String
    Public Property KG_start As Nullable(Of Decimal)
    Public Property KG_End As Nullable(Of Decimal)
    Public Property CUM_start As Nullable(Of Decimal)
    Public Property CUM_end As Nullable(Of Decimal)
    Public Property PRECIO_ECONOMICO As Nullable(Of Decimal)
    Public Property DIA_SIGUIENTE_BASE As Nullable(Of Decimal)
    Public Property DIA_SIGUIENTE_KILO As Nullable(Of Decimal)
    Public Property is_deleted As Nullable(Of Integer)

End Class
