'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ActivityLog
    Public Property Id As Integer
    Public Property Comment As String
    Public Property IpAddress As String
    Public Property EntityName As String
    Public Property ActivityLogTypeId As Integer
    Public Property CustomerId As Integer
    Public Property EntityId As Nullable(Of Integer)
    Public Property CreatedOnUtc As Date

    Public Overridable Property ActivityLogType As ActivityLogType

End Class
