'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ActivityLogType
    Public Property Id As Integer
    Public Property SystemKeyword As String
    Public Property Name As String
    Public Property Enabled As Boolean

    Public Overridable Property ActivityLogs As ICollection(Of ActivityLog) = New HashSet(Of ActivityLog)

End Class
