'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderItem
    Public Property Id As Integer
    Public Property OrderId As Integer
    Public Property ProductId As Integer
    Public Property OrderItemGuid As System.Guid
    Public Property Quantity As Integer
    Public Property UnitPriceInclTax As Decimal
    Public Property UnitPriceExclTax As Decimal
    Public Property PriceInclTax As Decimal
    Public Property PriceExclTax As Decimal
    Public Property DiscountAmountInclTax As Decimal
    Public Property DiscountAmountExclTax As Decimal
    Public Property OriginalProductCost As Decimal
    Public Property AttributeDescription As String
    Public Property AttributesXml As String
    Public Property DownloadCount As Integer
    Public Property IsDownloadActivated As Boolean
    Public Property LicenseDownloadId As Nullable(Of Integer)
    Public Property ItemWeight As Nullable(Of Decimal)
    Public Property RentalStartDateUtc As Nullable(Of Date)
    Public Property RentalEndDateUtc As Nullable(Of Date)

    Public Overridable Property Order As Order

End Class
