'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrdersVW
    Public Property Items As Nullable(Of Integer)
    Public Property Oderder_ID As Integer
    Public Property Customer_id As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Pais As String
    Public Property Estado As String
    Public Property Empresa As String
    Public Property Direccion As String
    Public Property Colonia As String
    Public Property CP As String
    Public Property Telefono As String
    Public Property Correo As String
    Public Property Cantidad As Integer
    Public Property Total As Decimal
    Public Property Total_Impuestos As Decimal

End Class
