'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderNote
    Public Property Id As Integer
    Public Property Note As String
    Public Property OrderId As Integer
    Public Property DownloadId As Integer
    Public Property DisplayToCustomer As Boolean
    Public Property CreatedOnUtc As Date

    Public Overridable Property Order As Order

End Class
