'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property Id As Integer
    Public Property CustomOrderNumber As String
    Public Property BillingAddressId As Integer
    Public Property CustomerId As Integer
    Public Property PickupAddressId As Nullable(Of Integer)
    Public Property ShippingAddressId As Nullable(Of Integer)
    Public Property OrderGuid As System.Guid
    Public Property StoreId As Integer
    Public Property PickupInStore As Boolean
    Public Property OrderStatusId As Integer
    Public Property ShippingStatusId As Integer
    Public Property PaymentStatusId As Integer
    Public Property PaymentMethodSystemName As String
    Public Property CustomerCurrencyCode As String
    Public Property CurrencyRate As Decimal
    Public Property CustomerTaxDisplayTypeId As Integer
    Public Property VatNumber As String
    Public Property OrderSubtotalInclTax As Decimal
    Public Property OrderSubtotalExclTax As Decimal
    Public Property OrderSubTotalDiscountInclTax As Decimal
    Public Property OrderSubTotalDiscountExclTax As Decimal
    Public Property OrderShippingInclTax As Decimal
    Public Property OrderShippingExclTax As Decimal
    Public Property PaymentMethodAdditionalFeeInclTax As Decimal
    Public Property PaymentMethodAdditionalFeeExclTax As Decimal
    Public Property TaxRates As String
    Public Property OrderTax As Decimal
    Public Property OrderDiscount As Decimal
    Public Property OrderTotal As Decimal
    Public Property RefundedAmount As Decimal
    Public Property RewardPointsHistoryEntryId As Nullable(Of Integer)
    Public Property CheckoutAttributeDescription As String
    Public Property CheckoutAttributesXml As String
    Public Property CustomerLanguageId As Integer
    Public Property AffiliateId As Integer
    Public Property CustomerIp As String
    Public Property AllowStoringCreditCardNumber As Boolean
    Public Property CardType As String
    Public Property CardName As String
    Public Property CardNumber As String
    Public Property MaskedCreditCardNumber As String
    Public Property CardCvv2 As String
    Public Property CardExpirationMonth As String
    Public Property CardExpirationYear As String
    Public Property AuthorizationTransactionId As String
    Public Property AuthorizationTransactionCode As String
    Public Property AuthorizationTransactionResult As String
    Public Property CaptureTransactionId As String
    Public Property CaptureTransactionResult As String
    Public Property SubscriptionTransactionId As String
    Public Property PaidDateUtc As Nullable(Of Date)
    Public Property ShippingMethod As String
    Public Property ShippingRateComputationMethodSystemName As String
    Public Property CustomValuesXml As String
    Public Property Deleted As Boolean
    Public Property CreatedOnUtc As Date
    Public Property RedeemedRewardPointsEntryId As Nullable(Of Integer)

    Public Overridable Property OrderItems As ICollection(Of OrderItem) = New HashSet(Of OrderItem)
    Public Overridable Property OrderNotes As ICollection(Of OrderNote) = New HashSet(Of OrderNote)
    Public Overridable Property Shipments As ICollection(Of Shipment) = New HashSet(Of Shipment)

End Class
