'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShipmentItem
    Public Property Id As Integer
    Public Property ShipmentId As Integer
    Public Property OrderItemId As Integer
    Public Property Quantity As Integer
    Public Property WarehouseId As Integer

    Public Overridable Property Shipment As Shipment

End Class
