'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GombarECommerceEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GombarECommerceEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property OrderItems() As DbSet(Of OrderItem)
    Public Overridable Property OrderNotes() As DbSet(Of OrderNote)
    Public Overridable Property Orders_VW() As DbSet(Of OrdersVW)

End Class
